### ISSUE TITLE
ingame overlay doesnt work

### ISSUE THREAD

**Issue by zachwzt** [Piotrekol/StreamCompanion#115]
i put used the in game overlay set up but when i try to go to output patterns they say "Live tokens detected. Use OBS plugin or ingame overlay to read it" even though i already installed the ingame overlay

**Comment by Piotrekol** [comment]
This is already fixed, release should appear later today (#113). Meanwhile
ingame overlay setup from that new version is a drop-in replacement. You
can download it there
https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/28807122/artifacts

pt., 15.11.2019, 04:25 użytkownik zachwzt <notifications@github.com>
napisał:

**Comment by zachwzt** [comment]
It still didnt fix the issue

**Comment by Piotrekol** [comment]
Then wait for next release.

pt., 15.11.2019, 10:57 użytkownik zachwzt <notifications@github.com>
napisał:

**Comment by zachwzt** [comment]
alright

**Comment by SaaYio** [comment]
Even after this update in-game overlay still does not work for me.

**Comment by zachwzt** [comment]
yea the new update still doesnt work for me:(

**Comment by Piotrekol** [comment]
any update on this? 
have you reinstalled ingameOverlay as requested in changelog? 
> (re-install ingameOverlay using setup provided below)

**Comment by zachwzt** [comment]
yea I reinstalled everything but it still doesn't work and I can only use the in-game overlay set up to set it up but it will still give me the live tokens thing and if i manually drop it in it gives me an error

**Comment by zachwzt** [comment]
i got it working and the live tokens thing was still appearing but i got it to work but when i closed osu and stream companion and opened it again the overlay didnt load it said to restart osu and so i did but it still didnt load in

**Comment by zachwzt** [comment]
the ingame overlay stopped working again. it stopped appearing

**Comment by Piotrekol** [comment]
(Since you haven't said anything, I'm assuming you're running on cutting edge)
I had no issues whatsoever running overlay on osu! stable. However, after changing to cutting edge, I could hardly ever get it to load, due to it first running osu! updater with is completely separate process.

Re-install using in-game overlay setup from this link and report back, thanks: https://ci.appveyor.com/api/buildjobs/yanmxe5sesl9yf2r/artifacts/innoSetup%2FOutput%2FStreamCompanion%20-%20ingameOverlay%20Setup.exe

**Comment by SaaYio** [comment]
Thanks this new link works for me

**Comment by zachwzt** [comment]
could the probelm be because im running on a private server? do i need to be on bancho for this to work?

**Comment by zachwzt** [comment]
tried the new link but the ingame overlay doesnt work the visualiser does tho

**Comment by Piotrekol** [comment]
> could the probelm be because im running on a private server

that is most likely the reason.
SC does not support unofficial osu! builds. SC working on any of these is purely coincidence and it can break at any moment.

**Comment by zachwzt** [comment]
i retried on bancho and reinstalled everything but it still doesnt work im confused
